import type { Metadata } from "next";
import { Noto_Serif_KR, Noto_Sans_KR, IBM_Plex_Mono } from "next/font/google";
import Sidebar from "@/components/Sidebar";
import styles from "./layout.module.css";
import "./globals.css";

const notoSerifKR = Noto_Serif_KR({
  variable: "--font-display",
  weight: "700",
  subsets: ["latin"],
});

const notoSansKR = Noto_Sans_KR({
  variable: "--font-body",
  weight: ["400", "500"],
  subsets: ["latin"],
});

const ibmPlexMono = IBM_Plex_Mono({
  variable: "--font-mono",
  weight: ["400", "500"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${notoSerifKR.variable} ${notoSansKR.variable} ${ibmPlexMono.variable}`}
    >
      <body>
        <div className={styles.shell}>
          <Sidebar />
          <main className={styles.main}>{children}</main>
        </div>
      </body>
    </html>
  );
}
